"""Shared types for LLM providers.

All types are provider-agnostic and serialize to the OpenAI chat format (ADR-002).
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import Any, Literal

Role = Literal["system", "user", "assistant", "tool"]


@dataclass(frozen=True)
class ToolCall:
    """A tool invocation requested by the model.

    Attributes:
        id: Unique call id (generated by us when the provider does not supply one).
        name: Tool name.
        arguments: Already-parsed arguments (never a raw JSON string).
    """

    id: str
    name: str
    arguments: dict[str, Any] = field(default_factory=dict)

    def to_openai(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "type": "function",
            "function": {"name": self.name, "arguments": json.dumps(self.arguments)},
        }


@dataclass(frozen=True)
class Message:
    """A single chat message."""

    role: Role
    content: str | None = None
    tool_calls: tuple[ToolCall, ...] = ()
    tool_call_id: str | None = None
    name: str | None = None

    def to_openai(self) -> dict[str, Any]:
        data: dict[str, Any] = {"role": self.role, "content": self.content}
        if self.tool_calls:
            data["tool_calls"] = [tc.to_openai() for tc in self.tool_calls]
        if self.tool_call_id is not None:
            data["tool_call_id"] = self.tool_call_id
        if self.name is not None:
            data["name"] = self.name
        return data


@dataclass(frozen=True)
class TokenUsage:
    """Token accounting. Fields are optional: providers do not always report them."""

    prompt_tokens: int | None = None
    completion_tokens: int | None = None
    total_tokens: int | None = None


@dataclass(frozen=True)
class LLMResponse:
    """Complete (non-streamed) response."""

    message: Message
    model: str
    provider: str
    usage: TokenUsage | None = None
    finish_reason: str | None = None


@dataclass(frozen=True)
class StreamChunk:
    """Incremental piece of a streamed response.

    Tool calls are emitted complete (providers accumulate fragments), usually in
    the final chunk, which also carries ``finish_reason`` and ``usage``.
    """

    delta: str = ""
    tool_calls: tuple[ToolCall, ...] = ()
    usage: TokenUsage | None = None
    finish_reason: str | None = None
